services:
  graphhopper-service:  
    image: israelhikingmap/graphhopper:9.1
    environment:
      - JAVA_OPTS=-Xmx100m -Xms100m
      - GRAPH_OPTS=-Ddw.graphhopper.datareader.file=data/college-park.osm.pbf -Ddw.graphhopper.graph.location=data/graph-cache
    volumes:
      - "./services/graphhopper/:/graphhopper/data/"
    networks:
      - backend-network
    command: ["-i", "data/college-park.osm.pbf", "-c", "data/config.yml"]
  
  api-service:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    environment:
      - PORT=8005
    networks:
      - backend-network

  scraper-service:
    environment:
    - TZ=America/New_York
    build:
      context: ./services/scraper
      dockerfile: Dockerfile

  redis:
    image: redis:latest
    restart: always
    networks:
      - backend_network  
      
networks:
  backend-network:
    driver: bridge 